name: 🐞 Bug report
description: Report a bug in the RealWorld Angular starter project
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: dropdown
    id: contribute
    attributes:
      label: Do you want to contribute with a pull request?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
