blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/orgs/realworld-angular/discussions
    about: Have a question or want to discuss something?
  - name: Documentation and API repository
    url: https://github.com/realworld-angular/realworld-angular
    about: Documentation and API for RealWorld Angular
